# Generated by Django 4.2.4 on 2023-08-06 17:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='server_counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.PositiveBigIntegerField()),
                ('counter_limit', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='short_url',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('short_url', models.CharField(blank=True, max_length=7, null=True, unique=True)),
                ('long_url', models.CharField(max_length=2048)),
                ('created_date', models.DateField(default=datetime.date.today)),
                ('visits', models.PositiveIntegerField(blank=True, default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
