# Generated by Django 4.2.4 on 2023-08-08 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('URLs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='short_url',
            name='qrcode',
            field=models.ImageField(blank=True, upload_to='qrcodes/'),
        ),
    ]
